#!/bin/bash
# F3b Cleanup Script: Remove misplaced feature tables from source_v2
# Generated by QA Agent: December 9, 2025
# STATUS: AWAITING CE APPROVAL - DO NOT EXECUTE
#
# Summary:
# - 101 misplaced tables in bqx_bq_uscen1_v2
# - 56 DUPLICATES (exist in features_v2)
# - 45 ORPHANS (reg_bqx, reg_corr_*, regime_*)
# - Total size: 96.95 GB
# - Monthly savings: ~$1.94
#
# IMPORTANT: Only DUPLICATE tables are safe to delete automatically.
# ORPHAN tables need manual review.

set -e

PROJECT="bqx-ml"
DATASET="bqx_bq_uscen1_v2"

echo "=== F3b Cleanup: Misplaced Tables in $DATASET ==="
echo "Date: $(date)"
echo ""

# PHASE 1: Delete DUPLICATE tables (exist in both source and features_v2)
# These are safe to delete as they have copies in features_v2

DUPLICATE_TABLES=(
    "reg_audcad"
    "reg_audchf"
    "reg_audjpy"
    "reg_audnzd"
    "reg_audusd"
    "reg_bqx_audcad"
    "reg_bqx_audchf"
    "reg_bqx_audjpy"
    "reg_bqx_audnzd"
    "reg_bqx_audusd"
    "reg_bqx_cadchf"
    "reg_bqx_cadjpy"
    "reg_bqx_chfjpy"
    "reg_bqx_euraud"
    "reg_bqx_eurcad"
    "reg_bqx_eurchf"
    "reg_bqx_eurgbp"
    "reg_bqx_eurjpy"
    "reg_bqx_eurnzd"
    "reg_bqx_eurusd"
    "reg_bqx_gbpaud"
    "reg_bqx_gbpcad"
    "reg_bqx_gbpchf"
    "reg_bqx_gbpjpy"
    "reg_bqx_gbpnzd"
    "reg_bqx_gbpusd"
    "reg_bqx_nzdcad"
    "reg_bqx_nzdchf"
    "reg_bqx_nzdjpy"
    "reg_bqx_nzdusd"
    "reg_bqx_usdcad"
    "reg_bqx_usdchf"
    "reg_bqx_usdjpy"
    "reg_cadchf"
    "reg_cadjpy"
    "reg_chfjpy"
    "reg_euraud"
    "reg_eurcad"
    "reg_eurchf"
    "reg_eurgbp"
    "reg_eurjpy"
    "reg_eurnzd"
    "reg_eurusd"
    "reg_gbpaud"
    "reg_gbpcad"
    "reg_gbpchf"
    "reg_gbpjpy"
    "reg_gbpnzd"
    "reg_gbpusd"
    "reg_nzdcad"
    "reg_nzdchf"
    "reg_nzdjpy"
    "reg_nzdusd"
    "reg_usdcad"
    "reg_usdchf"
    "reg_usdjpy"
)

echo "PHASE 1: Deleting ${#DUPLICATE_TABLES[@]} DUPLICATE tables..."
echo ""

for table in "${DUPLICATE_TABLES[@]}"; do
    echo "Deleting: $PROJECT:$DATASET.$table"
    bq rm -f "$PROJECT:$DATASET.$table"
done

echo ""
echo "Phase 1 complete: ${#DUPLICATE_TABLES[@]} duplicate tables deleted"
echo ""

# PHASE 2: ORPHAN tables - MANUAL REVIEW REQUIRED
# These tables only exist in source_v2, not in features_v2
# Decision needed: migrate to features_v2 or delete?

ORPHAN_TABLES=(
    "reg_bqx"
    "reg_corr_ewa"
    "reg_corr_ewg"
    "reg_corr_ewj"
    "reg_corr_ewu"
    "reg_corr_gld"
    "reg_corr_spy"
    "reg_corr_uup"
    "reg_corr_vix"
    "regime_audcad"
    "regime_audchf"
    "regime_audjpy"
    "regime_audnzd"
    "regime_audusd"
    "regime_cadchf"
    "regime_cadjpy"
    "regime_chfjpy"
    "regime_corr_ewa"
    "regime_corr_ewg"
    "regime_corr_ewj"
    "regime_corr_ewu"
    "regime_corr_gld"
    "regime_corr_spy"
    "regime_corr_uup"
    "regime_corr_vix"
    "regime_euraud"
    "regime_eurcad"
    "regime_eurchf"
    "regime_eurgbp"
    "regime_eurjpy"
    "regime_eurnzd"
    "regime_eurusd"
    "regime_gbpaud"
    "regime_gbpcad"
    "regime_gbpchf"
    "regime_gbpjpy"
    "regime_gbpnzd"
    "regime_gbpusd"
    "regime_nzdcad"
    "regime_nzdchf"
    "regime_nzdjpy"
    "regime_nzdusd"
    "regime_usdcad"
    "regime_usdchf"
    "regime_usdjpy"
)

echo "PHASE 2: ORPHAN tables requiring CE decision"
echo "Count: ${#ORPHAN_TABLES[@]} tables"
echo ""
echo "Options:"
echo "  A) Delete all orphans (if not needed for training)"
echo "  B) Migrate to features_v2 (if needed for training)"
echo ""

# Uncomment below to delete orphans after CE approval
# for table in "${ORPHAN_TABLES[@]}"; do
#     echo "Deleting orphan: $PROJECT:$DATASET.$table"
#     bq rm -f "$PROJECT:$DATASET.$table"
# done

echo "=== Cleanup Summary ==="
echo "Duplicates deleted: ${#DUPLICATE_TABLES[@]}"
echo "Orphans pending: ${#ORPHAN_TABLES[@]}"
echo "Total: $((${#DUPLICATE_TABLES[@]} + ${#ORPHAN_TABLES[@]}))"
echo ""
echo "Storage freed (estimated): ~97 GB"
echo "Monthly savings: ~\$1.94"
